runtime: nodejs
env: flex
env_variables:
  DATABASE_URL: "postgresql://postgres:a6s5d1f&^IDS&^@chat-app.cux8m74ubqle.ap-south-1.rds.amazonaws.com:5432/postgres"
  GOOGLE_CLIENT_ID='1020854869671-mk8h2s2iburg333vqhdibqb5i1mh4jl8.apps.googleusercontent.com'
  PORT: '8080'
  JWT_SECRET: "yyrasd<^8asd9QHR:}~dLasdAcv7~;e"